class_name Enums
extends Node

enum BaseState { IDLE, MOVE, SPRINT, CROUCH_IDLE, CROUCH_MOVE, JUMP, FALL, FREEHANG_IDLE, FREEHANG_MOVE, BRACED_IDLE, BRACED_MOVE, DIE, STUN, DROP, }
enum PostureState { STAND, COUCH, FREEHANG, BRACE, }
